language: Python
Python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pip install -e .
  - python ./tests/test_1.py
